### ISSUE TITLE
gamesense.pub - The “Time-zone” drop-down is misaligned

### ISSUE THREAD

**Issue by softvision-miralobontiu** [webcompat/webcompat-tests#1607]
**URL**: https://gamesense.pub/forums/register.php

**Browser / Version**: Firefox Nightly 63.0a1 (2018-07-09)
**Operating System**: Windows 10
**Tested Another Browser**: Yes

**Problem type**: Design is broken
**Description**: The “Time-zone” drop-down is misaligned
**Steps to Reproduce**:
1. Navigate to https://gamesense.pub/forums/register.php 
2. Observe the “Time-zone” drop-down.

**Expected Behavior:**
The drop-down is aligned.
 
**Actual Behavior:**
The drop-down is misaligned.

**Notes:**
1. Not reproducible on Chrome 67.0.3396.87.
2. Reproducible on Firefox Release 61.0.
3. Screenshot attached.

**Affected area**
```html
<select id="time_zone" name="timezone">
	<option value="-12">(UTC-12:00) International Date Line West</option>
	<option value="-11">(UTC-11:00) Niue, Samoa</option>
	<option value="-10">(UTC-10:00) Hawaii-Aleutian, Cook Island</option>
<!--cut-->
```

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; country: us
[![Screenshot Description](https://staging.webcompat.com/uploads/2018/7/40273d3c-fdf1-4476-8976-92ac6d5cd738-thumb.jpg)](https://staging.webcompat.com/uploads/2018/7/40273d3c-fdf1-4476-8976-92ac6d5cd738.jpg)

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by oword** [comment]
fixed!

**Comment by softvision-oana-arbuzov** [comment]
The drop-down is misaligned on mobile both Firefox and Chrome, but is is displayed correctly on desktop.
![image](https://user-images.githubusercontent.com/12184325/104036142-b74e9400-51db-11eb-8f8f-84047ea5c374.png)
![image](https://user-images.githubusercontent.com/12184325/104036582-3e9c0780-51dc-11eb-9623-25f78cb489e9.png)

**Tested with:**
Browser / Version: Firefox Nightly 86.0a1 (2021-01-08), Firefox Nightly 210107 (🦎 86.0a1-20210107040715), Chrome 87.0.4280.141
Operating System: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density) , Windows 10 Pro

Closing the issue as Worksforme.
