### ISSUE TITLE
helloworld.com - design is broken

### ISSUE THREAD

**Issue by magbello157** [webcompat/webcompat-tests#1954]
**URL**: http://helloworld.com

**Browser / Version**: Firefox 69.0
**Operating System**: Ubuntu
**Tested Another Browser**: Yes

**Problem type**: Design is broken
**Description**: asdf
**Steps to Reproduce**:
asdfjkl;

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>None</li>
</ul>

</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by magbello157** [comment]
@miketaylr Kindly assist in permanently deleting this issue which I submitted mistakenly while testing out how Webcompat worked.

**Comment by miketaylr** [comment]
@meetmuhd it's ok, this is a test repository. no harm done.
