### ISSUE TITLE
www.facebook.com - site is not usable

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-tests#2002]
**URL**: https://www.facebook.com/

**Browser / Version**: Firefox 72.0
**Operating System**: Mac OS X 10.14
**Tested Another Browser**: Yes

**Problem type**: Site is not usable
**Description**: Unable to type
**Steps to Reproduce**:
i was on facebok and then i couldn't do anything
[![Screenshot Description](https://staging.webcompat.com/uploads/2019/10/e662e5df-7a63-404f-8e03-c02c71694737-thumb.jpeg)](https://staging.webcompat.com/uploads/2019/10/e662e5df-7a63-404f-8e03-c02c71694737.jpeg)

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>gfx.webrender.all: false</li><li>gfx.webrender.blob-images: true</li><li>gfx.webrender.enabled: false</li><li>image.mem.shared: true</li><li>buildID: 20191022094606</li><li>channel: nightly</li><li>hasTouchScreen: false</li><li>mixed active content blocked: false</li><li>mixed passive content blocked: false</li><li>tracking content blocked: false</li>
</ul>
<p>Console Messages:</p>
<pre>
[{'level': 'timeStamp', 'log': ['t_start'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'warn', 'log': ['This page uses the non standard property zoom. Consider using calc() in the relevant property values, or using transform along with transform-origin: 0 0.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}, {'level': 'timeStamp', 'log': ['t_domcontent'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'timeStamp', 'log': ['t_tti'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'warn', 'log': ['onmozfullscreenchange is deprecated.'], 'uri': 'https://static.xx.fbcdn.net/rsrc.php/v3/y6/r/S3aWJpKfsOd.js?_nc_x=Ij3Wp8lg5Kz', 'pos': '273:5588'}, {'level': 'log', 'log': ['\n\n\n                                            \n .d8888b.  888                       888    \nd88P  Y88b 888                       888    \nY88b.      888                       888    This is a browser feature intended for \n "Y888b.   888888  .d88b.  88888b.   888    developers. If someone told you to copy-paste \n    "Y88b. 888    d88""88b 888 "88b  888    something here to enable a Facebook feature \n      "888 888    888  888 888  888  Y8P    or "hack" someone\'s account, it is a \nY88b  d88P Y88b.  Y88..88P 888 d88P         scam and will give them access to your \n "Y8888P"   "Y888  "Y88P"  88888P"   888    Facebook account.\n                           888              \n                           888              \n                           888              \n\nSee https://www.facebook.com/selfxss for more information.\n'], 'uri': 'https://static.xx.fbcdn.net/rsrc.php/v3iqES4/yS/l/en_US/FIqOd-kqWWn.js?_nc_x=Ij3Wp8lg5Kz', 'pos': '16:1486'}, {'level': 'timeStamp', 'log': ['t_prehooks'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'timeStamp', 'log': ['t_hooks'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'timeStamp', 'log': ['t_layout'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'timeStamp', 'log': ['perf_trace {"name": "e2e", "parent": "PageEvents.BIGPIPE_ONLOAD"}'], 'uri': 'https://static.xx.fbcdn.net/rsrc.php/v3/y6/r/S3aWJpKfsOd.js?_nc_x=Ij3Wp8lg5Kz', 'pos': '185:3039'}, {'level': 'timeStamp', 'log': ['t_paint'], 'uri': 'https://www.facebook.com/', 'pos': '3:1215'}, {'level': 'warn', 'log': ['Request to access cookie or storage on https://googleads.g.doubleclick.net/pagead/viewthroughconversion/995153884/?value=1.00&currency_code=USD&label=szBrCMnWkWAQ3K_D2gM&guid=ON&script=0 was blocked because it came from a tracker and content blocking is enabled.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}, {'level': 'warn', 'log': ['Content Security Policy: Ignoring x-frame-options because of frame-ancestors directive.'], 'uri': '', 'pos': '0:0'}, {'level': 'warn', 'log': ['Request to access cookie or storage on https://googleads.g.doubleclick.net/pagead/viewthroughconversion/995153884/?value=1.00&currency_code=USD&label=szBrCMnWkWAQ3K_D2gM&guid=ON&script=0 was blocked because it came from a tracker and content blocking is enabled.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}, {'level': 'warn', 'log': ['Request to access cookie or storage on https://www.google.com/pagead/1p-user-list/995153884/?value=1.00&currency_code=USD&label=szBrCMnWkWAQ3K_D2gM&guid=ON&script=0&is_vtc=1&random=1925489919 was blocked because it came from a tracker and content blocking is enabled.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}, {'level': 'warn', 'log': ['Request to access cookie or storage on https://www.google.com/pagead/1p-user-list/995153884/?value=1.00&currency_code=USD&label=szBrCMnWkWAQ3K_D2gM&guid=ON&script=0&is_vtc=1&random=1925489919 was blocked because it came from a tracker and content blocking is enabled.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}, {'level': 'warn', 'log': ['Request to access cookie or storage on https://www.google.com/pagead/1p-user-list/995153884/?value=1.00&currency_code=USD&label=szBrCMnWkWAQ3K_D2gM&guid=ON&script=0&is_vtc=1&random=1925489919 was blocked because it came from a tracker and content blocking is enabled.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}, {'level': 'warn', 'log': ['Request to access cookie or storage on https://www.google.com/pagead/1p-user-list/995153884/?value=1.00&currency_code=USD&label=szBrCMnWkWAQ3K_D2gM&guid=ON&script=0&is_vtc=1&random=1925489919 was blocked because it came from a tracker and content blocking is enabled.'], 'uri': 'https://www.facebook.com/', 'pos': '0:0'}]
</pre>
</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by Luciver90** [comment]
![image](https://user-images.githubusercontent.com/90346036/136081808-0bbb94b5-dd84-4be1-a445-882436100c3a.jpeg)
