### ISSUE TITLE
some broken URL - this site doesnt work 0.5434409996960312

### ISSUE THREAD

**Issue by GIGANTOR** [webcompat/webcompat-tests#222]
**URL**: some broken URL
**Browser / Version**: Firefox 31.0
**Operating System**: Mac OS X 10.10
**Problem type**: Unknown
**Site owner**: Unknown

**Steps to Reproduce**
1) Navigate to: some broken URL
2) …

Expected Behavior:
Actual Behavior:

**Comment by miketaylr** [comment]
test ping @magsout
