### ISSUE TITLE
miketaylr.com - site is weird

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-tests#228]
**URL**: miketaylr.com
**Browser / Version**: Firefox 35.0
**Operating System**: Mac OS X 10.10
**Problem type**: Unknown
**Site owner**: Unknown

**Steps to Reproduce**
1) Navigate to: miketaylr.com
2) …

Expected Behavior:
Actual Behavior:

**Comment by magsout** [comment]
```css
.test {
  color:red;
}
```

**Comment by magsout** [comment]
```js
.foo {
  return
}
```
