### ISSUE TITLE
mdpr.jp - layout is messed up

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat-tests#251]
**URL**: http://mdpr.jp/
**Browser / Version**: Firefox 38.0.5
**Operating System**: Android 5.1.1
**Problem type**: Layout is messed up

**Steps to Reproduce**
1) Navigate to: http://mdpr.jp/
2) Navigation bar is missing when the site is rendered
If we do some actions, like scrolling down, the navigation bar will appear and never go away.

Expected Behavior:
Navigation bar is placed on the top of the page.

Actual Behavior:
Navigation bar is missing.

country: jp

**Comment by miketaylr** [comment]
ok lol

**Comment by miketaylr** [comment]
#hi

**Comment by miketaylr** [comment]
*should 
*this
*be
*ok

**Comment by miketaylr** [comment]
#hi

**Comment by miketaylr** [comment]
*hi

**Comment by miketaylr** [comment]
* one

**Comment by miketaylr** [comment]
# hello

**Comment by magsout** [comment]
@miketaylr  pong

**Comment by miketaylr** [comment]
:)
