### ISSUE TITLE
localhost - desktop site instead of mobile site

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-tests#272]
**URL**: http://localhost/
**Browser / Version**: Firefox 42.0
**Operating System**: Mac OS X 10.10
**Problem type**: Desktop site instead of mobile site

**Steps to Reproduce**
1) Navigate to: http://localhost/
2) …

Expected Behavior: This is a test

Actual Behavior: Just a test

![751a802ba7b56cd1f5d1170fda195a06_1433859324.jpg](http://localhost:5000/uploads/751a802ba7b56cd1f5d1170fda195a06_1433859324.jpg)

**Comment by miketaylr** [comment]
![Screenshot of the site issue](http://localhost:5000/uploads/2015/9/d2496432-77f7-4fd5-ae57-fc239ff3d489.png)

**Comment by miketaylr** [comment]
![Screenshot of the site issue](http://localhost:5000/uploads/2015/9/900a728b-5b17-494e-962e-87341bcd991a.png)
