### ISSUE TITLE
www.final-test.com - video doesn't play

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-tests#276]
**URL**: www.final-test.com
**Browser / Version**: Firefox 42.0
**Operating System**: Mac OS X 10.10
**Problem type**: Video doesn't play

**Steps to Reproduce**
1) Navigate to: www.final-test.com
2) …

Expected Behavior:

Actual Behavior:

![2015/8/6552d275-eabe-4170-9117-f947bb007011.png](http://staging.webcompat.com/uploads/2015/8/6552d275-eabe-4170-9117-f947bb007011.png)

**Comment by miketaylr** [comment]
neat

**Comment by karlcow** [comment]
TEST001

**Comment by karlcow** [comment]
TEST002

**Comment by karlcow** [comment]
TEST003

**Comment by karlcow** [comment]
TEST004

**Comment by karlcow** [comment]
TEST005

**Comment by karlcow** [comment]
TEST006

![Screenshot of the site issue](http://localhost:5000/uploads/2015/9/ac1197d3-9082-4f05-8749-17b4b93383e3.png)
