### ISSUE TITLE
www.example.com - see bug description

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat-tests#400]
**URL**: http://www.example.com
**Browser / Version**: Firefox 46.0
**Operating System**: Windows 8.1
**Problem type**: Something else - I'll add details below

**Steps to Reproduce**
1) Navigate to: http://www.example.com
2) Test labels on webcompat.com

Expected Behavior: foo

Actual Behavior: bar

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by magsout** [comment]
test
