### ISSUE TITLE
www.thing.com - desktop site instead of mobile site

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-tests#509]
**URL**: www.thing.com
**Browser / Version**: Firefox 52.0
**Operating System**: Mac OS X 10.11
**Problem type**: Desktop site instead of mobile site

**Steps to Reproduce**
1. Navigate to: www.thing.com
2. …

Expected Behavior:

Actual Behavior:

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by karlcow** [comment]
foobar

**Comment by miketaylr** [comment]
ok

**Comment by miketaylr** [comment]
WONTFIX

**Comment by miketaylr** [comment]
actually, we will fix.

**Comment by miketaylr** [comment]
c

**Comment by miketaylr** [comment]
w

**Comment by miketaylr** [comment]
[![Screenshot Description](http://localhost:5000/uploads/2017/5/42ccf385-4733-46a5-8445-868f4ab8b12a-thumb.jpg)](http://localhost:5000/uploads/2017/5/42ccf385-4733-46a5-8445-868f4ab8b12a.jpg)

**Comment by karlcow** [comment]
![Screenshot of the site issue](http://staging.webcompat.com/uploads/2017/5/c9ac393e-7fb4-4d68-a2f8-f41a6355784d.jpg)

**Comment by karlcow** [comment]
[![Screenshot Description](http://localhost:5000/uploads/2017/5/ba7b3b75-4d9b-4a01-8862-7e28e432038d-thumb.jpg)](http://localhost:5000/uploads/2017/5/ba7b3b75-4d9b-4a01-8862-7e28e432038d.jpg)
