### ISSUE TITLE
adam.s - video doesn't play

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat-tests#513]
**URL**: http://adam.s
**Browser / Version**: Firefox 54.0
**Operating System**: Mac OS X 10.11
**Problem type**: Video doesn't play

**Steps to Reproduce**
1. Navigate to: http://adam.s
2. …

Expected Behavior:

Actual Behavior:

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by miketaylr** [comment]
cool dude

**Comment by miketaylr** [comment]
oops still a bug

**Comment by miketaylr** [comment]
lol not a bug

![Screenshot of the site issue](http://staging.webcompat.com/uploads/2017/4/9d788280-179d-49d3-a363-618ad69666c9.jpg)
