### ISSUE TITLE
QA watchers test - see bug description

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat-tests#545]
**URL**: QA watchers test
**Browser / Version**: Chrome 57.0.2987
**Operating System**: Windows 10
**Problem type**: Something else - I'll add details below

**Steps to Reproduce**
1. Navigate to: QA watchers test
2. …

Expected Behavior:

Actual Behavior:

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; country: blah

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by softvision-oana-arbuzov** [comment]
test
